/*
MailOdds Email Validation API

MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

API version: 1.0.0
Contact: support@mailodds.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailodds

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeliverRequestToInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeliverRequestToInner{}

// DeliverRequestToInner struct for DeliverRequestToInner
type DeliverRequestToInner struct {
	Email string `json:"email"`
	Name *string `json:"name,omitempty"`
}

type _DeliverRequestToInner DeliverRequestToInner

// NewDeliverRequestToInner instantiates a new DeliverRequestToInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeliverRequestToInner(email string) *DeliverRequestToInner {
	this := DeliverRequestToInner{}
	this.Email = email
	return &this
}

// NewDeliverRequestToInnerWithDefaults instantiates a new DeliverRequestToInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliverRequestToInnerWithDefaults() *DeliverRequestToInner {
	this := DeliverRequestToInner{}
	return &this
}

// GetEmail returns the Email field value
func (o *DeliverRequestToInner) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *DeliverRequestToInner) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *DeliverRequestToInner) SetEmail(v string) {
	o.Email = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DeliverRequestToInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliverRequestToInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DeliverRequestToInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DeliverRequestToInner) SetName(v string) {
	o.Name = &v
}

func (o DeliverRequestToInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeliverRequestToInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

func (o *DeliverRequestToInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeliverRequestToInner := _DeliverRequestToInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeliverRequestToInner)

	if err != nil {
		return err
	}

	*o = DeliverRequestToInner(varDeliverRequestToInner)

	return err
}

type NullableDeliverRequestToInner struct {
	value *DeliverRequestToInner
	isSet bool
}

func (v NullableDeliverRequestToInner) Get() *DeliverRequestToInner {
	return v.value
}

func (v *NullableDeliverRequestToInner) Set(val *DeliverRequestToInner) {
	v.value = val
	v.isSet = true
}

func (v NullableDeliverRequestToInner) IsSet() bool {
	return v.isSet
}

func (v *NullableDeliverRequestToInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeliverRequestToInner(val *DeliverRequestToInner) *NullableDeliverRequestToInner {
	return &NullableDeliverRequestToInner{value: val, isSet: true}
}

func (v NullableDeliverRequestToInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeliverRequestToInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


