/*
MailOdds Email Validation API

MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

API version: 1.0.0
Contact: support@mailodds.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailodds

import (
	"encoding/json"
)

// checks if the ValidationResponseSuppressionMatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidationResponseSuppressionMatch{}

// ValidationResponseSuppressionMatch struct for ValidationResponseSuppressionMatch
type ValidationResponseSuppressionMatch struct {
	Matched *bool `json:"matched,omitempty"`
	MatchType *string `json:"match_type,omitempty"`
	MatchValue *string `json:"match_value,omitempty"`
}

// NewValidationResponseSuppressionMatch instantiates a new ValidationResponseSuppressionMatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidationResponseSuppressionMatch() *ValidationResponseSuppressionMatch {
	this := ValidationResponseSuppressionMatch{}
	return &this
}

// NewValidationResponseSuppressionMatchWithDefaults instantiates a new ValidationResponseSuppressionMatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidationResponseSuppressionMatchWithDefaults() *ValidationResponseSuppressionMatch {
	this := ValidationResponseSuppressionMatch{}
	return &this
}

// GetMatched returns the Matched field value if set, zero value otherwise.
func (o *ValidationResponseSuppressionMatch) GetMatched() bool {
	if o == nil || IsNil(o.Matched) {
		var ret bool
		return ret
	}
	return *o.Matched
}

// GetMatchedOk returns a tuple with the Matched field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationResponseSuppressionMatch) GetMatchedOk() (*bool, bool) {
	if o == nil || IsNil(o.Matched) {
		return nil, false
	}
	return o.Matched, true
}

// HasMatched returns a boolean if a field has been set.
func (o *ValidationResponseSuppressionMatch) HasMatched() bool {
	if o != nil && !IsNil(o.Matched) {
		return true
	}

	return false
}

// SetMatched gets a reference to the given bool and assigns it to the Matched field.
func (o *ValidationResponseSuppressionMatch) SetMatched(v bool) {
	o.Matched = &v
}

// GetMatchType returns the MatchType field value if set, zero value otherwise.
func (o *ValidationResponseSuppressionMatch) GetMatchType() string {
	if o == nil || IsNil(o.MatchType) {
		var ret string
		return ret
	}
	return *o.MatchType
}

// GetMatchTypeOk returns a tuple with the MatchType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationResponseSuppressionMatch) GetMatchTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MatchType) {
		return nil, false
	}
	return o.MatchType, true
}

// HasMatchType returns a boolean if a field has been set.
func (o *ValidationResponseSuppressionMatch) HasMatchType() bool {
	if o != nil && !IsNil(o.MatchType) {
		return true
	}

	return false
}

// SetMatchType gets a reference to the given string and assigns it to the MatchType field.
func (o *ValidationResponseSuppressionMatch) SetMatchType(v string) {
	o.MatchType = &v
}

// GetMatchValue returns the MatchValue field value if set, zero value otherwise.
func (o *ValidationResponseSuppressionMatch) GetMatchValue() string {
	if o == nil || IsNil(o.MatchValue) {
		var ret string
		return ret
	}
	return *o.MatchValue
}

// GetMatchValueOk returns a tuple with the MatchValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationResponseSuppressionMatch) GetMatchValueOk() (*string, bool) {
	if o == nil || IsNil(o.MatchValue) {
		return nil, false
	}
	return o.MatchValue, true
}

// HasMatchValue returns a boolean if a field has been set.
func (o *ValidationResponseSuppressionMatch) HasMatchValue() bool {
	if o != nil && !IsNil(o.MatchValue) {
		return true
	}

	return false
}

// SetMatchValue gets a reference to the given string and assigns it to the MatchValue field.
func (o *ValidationResponseSuppressionMatch) SetMatchValue(v string) {
	o.MatchValue = &v
}

func (o ValidationResponseSuppressionMatch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidationResponseSuppressionMatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Matched) {
		toSerialize["matched"] = o.Matched
	}
	if !IsNil(o.MatchType) {
		toSerialize["match_type"] = o.MatchType
	}
	if !IsNil(o.MatchValue) {
		toSerialize["match_value"] = o.MatchValue
	}
	return toSerialize, nil
}

type NullableValidationResponseSuppressionMatch struct {
	value *ValidationResponseSuppressionMatch
	isSet bool
}

func (v NullableValidationResponseSuppressionMatch) Get() *ValidationResponseSuppressionMatch {
	return v.value
}

func (v *NullableValidationResponseSuppressionMatch) Set(val *ValidationResponseSuppressionMatch) {
	v.value = val
	v.isSet = true
}

func (v NullableValidationResponseSuppressionMatch) IsSet() bool {
	return v.isSet
}

func (v *NullableValidationResponseSuppressionMatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidationResponseSuppressionMatch(val *ValidationResponseSuppressionMatch) *NullableValidationResponseSuppressionMatch {
	return &NullableValidationResponseSuppressionMatch{value: val, isSet: true}
}

func (v NullableValidationResponseSuppressionMatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidationResponseSuppressionMatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


