/*
MailOdds Email Validation API

MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

API version: 1.0.0
Contact: support@mailodds.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailodds

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreatePolicyFromPresetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePolicyFromPresetRequest{}

// CreatePolicyFromPresetRequest struct for CreatePolicyFromPresetRequest
type CreatePolicyFromPresetRequest struct {
	PresetId string `json:"preset_id"`
	Name string `json:"name"`
	IsDefault *bool `json:"is_default,omitempty"`
}

type _CreatePolicyFromPresetRequest CreatePolicyFromPresetRequest

// NewCreatePolicyFromPresetRequest instantiates a new CreatePolicyFromPresetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePolicyFromPresetRequest(presetId string, name string) *CreatePolicyFromPresetRequest {
	this := CreatePolicyFromPresetRequest{}
	this.PresetId = presetId
	this.Name = name
	var isDefault bool = false
	this.IsDefault = &isDefault
	return &this
}

// NewCreatePolicyFromPresetRequestWithDefaults instantiates a new CreatePolicyFromPresetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePolicyFromPresetRequestWithDefaults() *CreatePolicyFromPresetRequest {
	this := CreatePolicyFromPresetRequest{}
	var isDefault bool = false
	this.IsDefault = &isDefault
	return &this
}

// GetPresetId returns the PresetId field value
func (o *CreatePolicyFromPresetRequest) GetPresetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PresetId
}

// GetPresetIdOk returns a tuple with the PresetId field value
// and a boolean to check if the value has been set.
func (o *CreatePolicyFromPresetRequest) GetPresetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PresetId, true
}

// SetPresetId sets field value
func (o *CreatePolicyFromPresetRequest) SetPresetId(v string) {
	o.PresetId = v
}

// GetName returns the Name field value
func (o *CreatePolicyFromPresetRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreatePolicyFromPresetRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreatePolicyFromPresetRequest) SetName(v string) {
	o.Name = v
}

// GetIsDefault returns the IsDefault field value if set, zero value otherwise.
func (o *CreatePolicyFromPresetRequest) GetIsDefault() bool {
	if o == nil || IsNil(o.IsDefault) {
		var ret bool
		return ret
	}
	return *o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePolicyFromPresetRequest) GetIsDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDefault) {
		return nil, false
	}
	return o.IsDefault, true
}

// HasIsDefault returns a boolean if a field has been set.
func (o *CreatePolicyFromPresetRequest) HasIsDefault() bool {
	if o != nil && !IsNil(o.IsDefault) {
		return true
	}

	return false
}

// SetIsDefault gets a reference to the given bool and assigns it to the IsDefault field.
func (o *CreatePolicyFromPresetRequest) SetIsDefault(v bool) {
	o.IsDefault = &v
}

func (o CreatePolicyFromPresetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePolicyFromPresetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["preset_id"] = o.PresetId
	toSerialize["name"] = o.Name
	if !IsNil(o.IsDefault) {
		toSerialize["is_default"] = o.IsDefault
	}
	return toSerialize, nil
}

func (o *CreatePolicyFromPresetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"preset_id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePolicyFromPresetRequest := _CreatePolicyFromPresetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatePolicyFromPresetRequest)

	if err != nil {
		return err
	}

	*o = CreatePolicyFromPresetRequest(varCreatePolicyFromPresetRequest)

	return err
}

type NullableCreatePolicyFromPresetRequest struct {
	value *CreatePolicyFromPresetRequest
	isSet bool
}

func (v NullableCreatePolicyFromPresetRequest) Get() *CreatePolicyFromPresetRequest {
	return v.value
}

func (v *NullableCreatePolicyFromPresetRequest) Set(val *CreatePolicyFromPresetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePolicyFromPresetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePolicyFromPresetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePolicyFromPresetRequest(val *CreatePolicyFromPresetRequest) *NullableCreatePolicyFromPresetRequest {
	return &NullableCreatePolicyFromPresetRequest{value: val, isSet: true}
}

func (v NullableCreatePolicyFromPresetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePolicyFromPresetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


