/*
MailOdds Email Validation API

MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

API version: 1.0.0
Contact: support@mailodds.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailodds

import (
	"encoding/json"
)

// checks if the UnsubscribeSubscriber200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnsubscribeSubscriber200Response{}

// UnsubscribeSubscriber200Response struct for UnsubscribeSubscriber200Response
type UnsubscribeSubscriber200Response struct {
	Subscriber *Subscriber `json:"subscriber,omitempty"`
}

// NewUnsubscribeSubscriber200Response instantiates a new UnsubscribeSubscriber200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnsubscribeSubscriber200Response() *UnsubscribeSubscriber200Response {
	this := UnsubscribeSubscriber200Response{}
	return &this
}

// NewUnsubscribeSubscriber200ResponseWithDefaults instantiates a new UnsubscribeSubscriber200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnsubscribeSubscriber200ResponseWithDefaults() *UnsubscribeSubscriber200Response {
	this := UnsubscribeSubscriber200Response{}
	return &this
}

// GetSubscriber returns the Subscriber field value if set, zero value otherwise.
func (o *UnsubscribeSubscriber200Response) GetSubscriber() Subscriber {
	if o == nil || IsNil(o.Subscriber) {
		var ret Subscriber
		return ret
	}
	return *o.Subscriber
}

// GetSubscriberOk returns a tuple with the Subscriber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnsubscribeSubscriber200Response) GetSubscriberOk() (*Subscriber, bool) {
	if o == nil || IsNil(o.Subscriber) {
		return nil, false
	}
	return o.Subscriber, true
}

// HasSubscriber returns a boolean if a field has been set.
func (o *UnsubscribeSubscriber200Response) HasSubscriber() bool {
	if o != nil && !IsNil(o.Subscriber) {
		return true
	}

	return false
}

// SetSubscriber gets a reference to the given Subscriber and assigns it to the Subscriber field.
func (o *UnsubscribeSubscriber200Response) SetSubscriber(v Subscriber) {
	o.Subscriber = &v
}

func (o UnsubscribeSubscriber200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnsubscribeSubscriber200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Subscriber) {
		toSerialize["subscriber"] = o.Subscriber
	}
	return toSerialize, nil
}

type NullableUnsubscribeSubscriber200Response struct {
	value *UnsubscribeSubscriber200Response
	isSet bool
}

func (v NullableUnsubscribeSubscriber200Response) Get() *UnsubscribeSubscriber200Response {
	return v.value
}

func (v *NullableUnsubscribeSubscriber200Response) Set(val *UnsubscribeSubscriber200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUnsubscribeSubscriber200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUnsubscribeSubscriber200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnsubscribeSubscriber200Response(val *UnsubscribeSubscriber200Response) *NullableUnsubscribeSubscriber200Response {
	return &NullableUnsubscribeSubscriber200Response{value: val, isSet: true}
}

func (v NullableUnsubscribeSubscriber200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnsubscribeSubscriber200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


