/*
MailOdds Email Validation API

MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

API version: 1.0.0
Contact: support@mailodds.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailodds

import (
	"encoding/json"
)

// checks if the GetSendingStats200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSendingStats200Response{}

// GetSendingStats200Response struct for GetSendingStats200Response
type GetSendingStats200Response struct {
	Stats *GetSendingStats200ResponseStats `json:"stats,omitempty"`
}

// NewGetSendingStats200Response instantiates a new GetSendingStats200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSendingStats200Response() *GetSendingStats200Response {
	this := GetSendingStats200Response{}
	return &this
}

// NewGetSendingStats200ResponseWithDefaults instantiates a new GetSendingStats200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSendingStats200ResponseWithDefaults() *GetSendingStats200Response {
	this := GetSendingStats200Response{}
	return &this
}

// GetStats returns the Stats field value if set, zero value otherwise.
func (o *GetSendingStats200Response) GetStats() GetSendingStats200ResponseStats {
	if o == nil || IsNil(o.Stats) {
		var ret GetSendingStats200ResponseStats
		return ret
	}
	return *o.Stats
}

// GetStatsOk returns a tuple with the Stats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendingStats200Response) GetStatsOk() (*GetSendingStats200ResponseStats, bool) {
	if o == nil || IsNil(o.Stats) {
		return nil, false
	}
	return o.Stats, true
}

// HasStats returns a boolean if a field has been set.
func (o *GetSendingStats200Response) HasStats() bool {
	if o != nil && !IsNil(o.Stats) {
		return true
	}

	return false
}

// SetStats gets a reference to the given GetSendingStats200ResponseStats and assigns it to the Stats field.
func (o *GetSendingStats200Response) SetStats(v GetSendingStats200ResponseStats) {
	o.Stats = &v
}

func (o GetSendingStats200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSendingStats200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Stats) {
		toSerialize["stats"] = o.Stats
	}
	return toSerialize, nil
}

type NullableGetSendingStats200Response struct {
	value *GetSendingStats200Response
	isSet bool
}

func (v NullableGetSendingStats200Response) Get() *GetSendingStats200Response {
	return v.value
}

func (v *NullableGetSendingStats200Response) Set(val *GetSendingStats200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSendingStats200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSendingStats200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSendingStats200Response(val *GetSendingStats200Response) *NullableGetSendingStats200Response {
	return &NullableGetSendingStats200Response{value: val, isSet: true}
}

func (v NullableGetSendingStats200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSendingStats200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


