/*
MailOdds Email Validation API

MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

API version: 1.0.0
Contact: support@mailodds.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailodds

import (
	"encoding/json"
)

// checks if the GetSendingStats200ResponseStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSendingStats200ResponseStats{}

// GetSendingStats200ResponseStats struct for GetSendingStats200ResponseStats
type GetSendingStats200ResponseStats struct {
	Period *string `json:"period,omitempty"`
	Sent *int32 `json:"sent,omitempty"`
	Delivered *int32 `json:"delivered,omitempty"`
	Bounced *int32 `json:"bounced,omitempty"`
	Deferred *int32 `json:"deferred,omitempty"`
	Failed *int32 `json:"failed,omitempty"`
	OpenedTotal *int32 `json:"opened_total,omitempty"`
	OpenedUnique *int32 `json:"opened_unique,omitempty"`
	ClickedTotal *int32 `json:"clicked_total,omitempty"`
	ClickedUnique *int32 `json:"clicked_unique,omitempty"`
	Unsubscribed *int32 `json:"unsubscribed,omitempty"`
	DeliveryRate *float32 `json:"delivery_rate,omitempty"`
	OpenRate *float32 `json:"open_rate,omitempty"`
	ClickRate *float32 `json:"click_rate,omitempty"`
	// Opens from known bots/scanners
	BotOpens *int32 `json:"bot_opens,omitempty"`
	// Verified human opens
	HumanOpens *int32 `json:"human_opens,omitempty"`
	// Percentage of opens from bots
	BotOpenPct *float32 `json:"bot_open_pct,omitempty"`
}

// NewGetSendingStats200ResponseStats instantiates a new GetSendingStats200ResponseStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSendingStats200ResponseStats() *GetSendingStats200ResponseStats {
	this := GetSendingStats200ResponseStats{}
	return &this
}

// NewGetSendingStats200ResponseStatsWithDefaults instantiates a new GetSendingStats200ResponseStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSendingStats200ResponseStatsWithDefaults() *GetSendingStats200ResponseStats {
	this := GetSendingStats200ResponseStats{}
	return &this
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *GetSendingStats200ResponseStats) GetPeriod() string {
	if o == nil || IsNil(o.Period) {
		var ret string
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendingStats200ResponseStats) GetPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *GetSendingStats200ResponseStats) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given string and assigns it to the Period field.
func (o *GetSendingStats200ResponseStats) SetPeriod(v string) {
	o.Period = &v
}

// GetSent returns the Sent field value if set, zero value otherwise.
func (o *GetSendingStats200ResponseStats) GetSent() int32 {
	if o == nil || IsNil(o.Sent) {
		var ret int32
		return ret
	}
	return *o.Sent
}

// GetSentOk returns a tuple with the Sent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendingStats200ResponseStats) GetSentOk() (*int32, bool) {
	if o == nil || IsNil(o.Sent) {
		return nil, false
	}
	return o.Sent, true
}

// HasSent returns a boolean if a field has been set.
func (o *GetSendingStats200ResponseStats) HasSent() bool {
	if o != nil && !IsNil(o.Sent) {
		return true
	}

	return false
}

// SetSent gets a reference to the given int32 and assigns it to the Sent field.
func (o *GetSendingStats200ResponseStats) SetSent(v int32) {
	o.Sent = &v
}

// GetDelivered returns the Delivered field value if set, zero value otherwise.
func (o *GetSendingStats200ResponseStats) GetDelivered() int32 {
	if o == nil || IsNil(o.Delivered) {
		var ret int32
		return ret
	}
	return *o.Delivered
}

// GetDeliveredOk returns a tuple with the Delivered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendingStats200ResponseStats) GetDeliveredOk() (*int32, bool) {
	if o == nil || IsNil(o.Delivered) {
		return nil, false
	}
	return o.Delivered, true
}

// HasDelivered returns a boolean if a field has been set.
func (o *GetSendingStats200ResponseStats) HasDelivered() bool {
	if o != nil && !IsNil(o.Delivered) {
		return true
	}

	return false
}

// SetDelivered gets a reference to the given int32 and assigns it to the Delivered field.
func (o *GetSendingStats200ResponseStats) SetDelivered(v int32) {
	o.Delivered = &v
}

// GetBounced returns the Bounced field value if set, zero value otherwise.
func (o *GetSendingStats200ResponseStats) GetBounced() int32 {
	if o == nil || IsNil(o.Bounced) {
		var ret int32
		return ret
	}
	return *o.Bounced
}

// GetBouncedOk returns a tuple with the Bounced field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendingStats200ResponseStats) GetBouncedOk() (*int32, bool) {
	if o == nil || IsNil(o.Bounced) {
		return nil, false
	}
	return o.Bounced, true
}

// HasBounced returns a boolean if a field has been set.
func (o *GetSendingStats200ResponseStats) HasBounced() bool {
	if o != nil && !IsNil(o.Bounced) {
		return true
	}

	return false
}

// SetBounced gets a reference to the given int32 and assigns it to the Bounced field.
func (o *GetSendingStats200ResponseStats) SetBounced(v int32) {
	o.Bounced = &v
}

// GetDeferred returns the Deferred field value if set, zero value otherwise.
func (o *GetSendingStats200ResponseStats) GetDeferred() int32 {
	if o == nil || IsNil(o.Deferred) {
		var ret int32
		return ret
	}
	return *o.Deferred
}

// GetDeferredOk returns a tuple with the Deferred field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendingStats200ResponseStats) GetDeferredOk() (*int32, bool) {
	if o == nil || IsNil(o.Deferred) {
		return nil, false
	}
	return o.Deferred, true
}

// HasDeferred returns a boolean if a field has been set.
func (o *GetSendingStats200ResponseStats) HasDeferred() bool {
	if o != nil && !IsNil(o.Deferred) {
		return true
	}

	return false
}

// SetDeferred gets a reference to the given int32 and assigns it to the Deferred field.
func (o *GetSendingStats200ResponseStats) SetDeferred(v int32) {
	o.Deferred = &v
}

// GetFailed returns the Failed field value if set, zero value otherwise.
func (o *GetSendingStats200ResponseStats) GetFailed() int32 {
	if o == nil || IsNil(o.Failed) {
		var ret int32
		return ret
	}
	return *o.Failed
}

// GetFailedOk returns a tuple with the Failed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendingStats200ResponseStats) GetFailedOk() (*int32, bool) {
	if o == nil || IsNil(o.Failed) {
		return nil, false
	}
	return o.Failed, true
}

// HasFailed returns a boolean if a field has been set.
func (o *GetSendingStats200ResponseStats) HasFailed() bool {
	if o != nil && !IsNil(o.Failed) {
		return true
	}

	return false
}

// SetFailed gets a reference to the given int32 and assigns it to the Failed field.
func (o *GetSendingStats200ResponseStats) SetFailed(v int32) {
	o.Failed = &v
}

// GetOpenedTotal returns the OpenedTotal field value if set, zero value otherwise.
func (o *GetSendingStats200ResponseStats) GetOpenedTotal() int32 {
	if o == nil || IsNil(o.OpenedTotal) {
		var ret int32
		return ret
	}
	return *o.OpenedTotal
}

// GetOpenedTotalOk returns a tuple with the OpenedTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendingStats200ResponseStats) GetOpenedTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.OpenedTotal) {
		return nil, false
	}
	return o.OpenedTotal, true
}

// HasOpenedTotal returns a boolean if a field has been set.
func (o *GetSendingStats200ResponseStats) HasOpenedTotal() bool {
	if o != nil && !IsNil(o.OpenedTotal) {
		return true
	}

	return false
}

// SetOpenedTotal gets a reference to the given int32 and assigns it to the OpenedTotal field.
func (o *GetSendingStats200ResponseStats) SetOpenedTotal(v int32) {
	o.OpenedTotal = &v
}

// GetOpenedUnique returns the OpenedUnique field value if set, zero value otherwise.
func (o *GetSendingStats200ResponseStats) GetOpenedUnique() int32 {
	if o == nil || IsNil(o.OpenedUnique) {
		var ret int32
		return ret
	}
	return *o.OpenedUnique
}

// GetOpenedUniqueOk returns a tuple with the OpenedUnique field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendingStats200ResponseStats) GetOpenedUniqueOk() (*int32, bool) {
	if o == nil || IsNil(o.OpenedUnique) {
		return nil, false
	}
	return o.OpenedUnique, true
}

// HasOpenedUnique returns a boolean if a field has been set.
func (o *GetSendingStats200ResponseStats) HasOpenedUnique() bool {
	if o != nil && !IsNil(o.OpenedUnique) {
		return true
	}

	return false
}

// SetOpenedUnique gets a reference to the given int32 and assigns it to the OpenedUnique field.
func (o *GetSendingStats200ResponseStats) SetOpenedUnique(v int32) {
	o.OpenedUnique = &v
}

// GetClickedTotal returns the ClickedTotal field value if set, zero value otherwise.
func (o *GetSendingStats200ResponseStats) GetClickedTotal() int32 {
	if o == nil || IsNil(o.ClickedTotal) {
		var ret int32
		return ret
	}
	return *o.ClickedTotal
}

// GetClickedTotalOk returns a tuple with the ClickedTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendingStats200ResponseStats) GetClickedTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.ClickedTotal) {
		return nil, false
	}
	return o.ClickedTotal, true
}

// HasClickedTotal returns a boolean if a field has been set.
func (o *GetSendingStats200ResponseStats) HasClickedTotal() bool {
	if o != nil && !IsNil(o.ClickedTotal) {
		return true
	}

	return false
}

// SetClickedTotal gets a reference to the given int32 and assigns it to the ClickedTotal field.
func (o *GetSendingStats200ResponseStats) SetClickedTotal(v int32) {
	o.ClickedTotal = &v
}

// GetClickedUnique returns the ClickedUnique field value if set, zero value otherwise.
func (o *GetSendingStats200ResponseStats) GetClickedUnique() int32 {
	if o == nil || IsNil(o.ClickedUnique) {
		var ret int32
		return ret
	}
	return *o.ClickedUnique
}

// GetClickedUniqueOk returns a tuple with the ClickedUnique field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendingStats200ResponseStats) GetClickedUniqueOk() (*int32, bool) {
	if o == nil || IsNil(o.ClickedUnique) {
		return nil, false
	}
	return o.ClickedUnique, true
}

// HasClickedUnique returns a boolean if a field has been set.
func (o *GetSendingStats200ResponseStats) HasClickedUnique() bool {
	if o != nil && !IsNil(o.ClickedUnique) {
		return true
	}

	return false
}

// SetClickedUnique gets a reference to the given int32 and assigns it to the ClickedUnique field.
func (o *GetSendingStats200ResponseStats) SetClickedUnique(v int32) {
	o.ClickedUnique = &v
}

// GetUnsubscribed returns the Unsubscribed field value if set, zero value otherwise.
func (o *GetSendingStats200ResponseStats) GetUnsubscribed() int32 {
	if o == nil || IsNil(o.Unsubscribed) {
		var ret int32
		return ret
	}
	return *o.Unsubscribed
}

// GetUnsubscribedOk returns a tuple with the Unsubscribed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendingStats200ResponseStats) GetUnsubscribedOk() (*int32, bool) {
	if o == nil || IsNil(o.Unsubscribed) {
		return nil, false
	}
	return o.Unsubscribed, true
}

// HasUnsubscribed returns a boolean if a field has been set.
func (o *GetSendingStats200ResponseStats) HasUnsubscribed() bool {
	if o != nil && !IsNil(o.Unsubscribed) {
		return true
	}

	return false
}

// SetUnsubscribed gets a reference to the given int32 and assigns it to the Unsubscribed field.
func (o *GetSendingStats200ResponseStats) SetUnsubscribed(v int32) {
	o.Unsubscribed = &v
}

// GetDeliveryRate returns the DeliveryRate field value if set, zero value otherwise.
func (o *GetSendingStats200ResponseStats) GetDeliveryRate() float32 {
	if o == nil || IsNil(o.DeliveryRate) {
		var ret float32
		return ret
	}
	return *o.DeliveryRate
}

// GetDeliveryRateOk returns a tuple with the DeliveryRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendingStats200ResponseStats) GetDeliveryRateOk() (*float32, bool) {
	if o == nil || IsNil(o.DeliveryRate) {
		return nil, false
	}
	return o.DeliveryRate, true
}

// HasDeliveryRate returns a boolean if a field has been set.
func (o *GetSendingStats200ResponseStats) HasDeliveryRate() bool {
	if o != nil && !IsNil(o.DeliveryRate) {
		return true
	}

	return false
}

// SetDeliveryRate gets a reference to the given float32 and assigns it to the DeliveryRate field.
func (o *GetSendingStats200ResponseStats) SetDeliveryRate(v float32) {
	o.DeliveryRate = &v
}

// GetOpenRate returns the OpenRate field value if set, zero value otherwise.
func (o *GetSendingStats200ResponseStats) GetOpenRate() float32 {
	if o == nil || IsNil(o.OpenRate) {
		var ret float32
		return ret
	}
	return *o.OpenRate
}

// GetOpenRateOk returns a tuple with the OpenRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendingStats200ResponseStats) GetOpenRateOk() (*float32, bool) {
	if o == nil || IsNil(o.OpenRate) {
		return nil, false
	}
	return o.OpenRate, true
}

// HasOpenRate returns a boolean if a field has been set.
func (o *GetSendingStats200ResponseStats) HasOpenRate() bool {
	if o != nil && !IsNil(o.OpenRate) {
		return true
	}

	return false
}

// SetOpenRate gets a reference to the given float32 and assigns it to the OpenRate field.
func (o *GetSendingStats200ResponseStats) SetOpenRate(v float32) {
	o.OpenRate = &v
}

// GetClickRate returns the ClickRate field value if set, zero value otherwise.
func (o *GetSendingStats200ResponseStats) GetClickRate() float32 {
	if o == nil || IsNil(o.ClickRate) {
		var ret float32
		return ret
	}
	return *o.ClickRate
}

// GetClickRateOk returns a tuple with the ClickRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendingStats200ResponseStats) GetClickRateOk() (*float32, bool) {
	if o == nil || IsNil(o.ClickRate) {
		return nil, false
	}
	return o.ClickRate, true
}

// HasClickRate returns a boolean if a field has been set.
func (o *GetSendingStats200ResponseStats) HasClickRate() bool {
	if o != nil && !IsNil(o.ClickRate) {
		return true
	}

	return false
}

// SetClickRate gets a reference to the given float32 and assigns it to the ClickRate field.
func (o *GetSendingStats200ResponseStats) SetClickRate(v float32) {
	o.ClickRate = &v
}

// GetBotOpens returns the BotOpens field value if set, zero value otherwise.
func (o *GetSendingStats200ResponseStats) GetBotOpens() int32 {
	if o == nil || IsNil(o.BotOpens) {
		var ret int32
		return ret
	}
	return *o.BotOpens
}

// GetBotOpensOk returns a tuple with the BotOpens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendingStats200ResponseStats) GetBotOpensOk() (*int32, bool) {
	if o == nil || IsNil(o.BotOpens) {
		return nil, false
	}
	return o.BotOpens, true
}

// HasBotOpens returns a boolean if a field has been set.
func (o *GetSendingStats200ResponseStats) HasBotOpens() bool {
	if o != nil && !IsNil(o.BotOpens) {
		return true
	}

	return false
}

// SetBotOpens gets a reference to the given int32 and assigns it to the BotOpens field.
func (o *GetSendingStats200ResponseStats) SetBotOpens(v int32) {
	o.BotOpens = &v
}

// GetHumanOpens returns the HumanOpens field value if set, zero value otherwise.
func (o *GetSendingStats200ResponseStats) GetHumanOpens() int32 {
	if o == nil || IsNil(o.HumanOpens) {
		var ret int32
		return ret
	}
	return *o.HumanOpens
}

// GetHumanOpensOk returns a tuple with the HumanOpens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendingStats200ResponseStats) GetHumanOpensOk() (*int32, bool) {
	if o == nil || IsNil(o.HumanOpens) {
		return nil, false
	}
	return o.HumanOpens, true
}

// HasHumanOpens returns a boolean if a field has been set.
func (o *GetSendingStats200ResponseStats) HasHumanOpens() bool {
	if o != nil && !IsNil(o.HumanOpens) {
		return true
	}

	return false
}

// SetHumanOpens gets a reference to the given int32 and assigns it to the HumanOpens field.
func (o *GetSendingStats200ResponseStats) SetHumanOpens(v int32) {
	o.HumanOpens = &v
}

// GetBotOpenPct returns the BotOpenPct field value if set, zero value otherwise.
func (o *GetSendingStats200ResponseStats) GetBotOpenPct() float32 {
	if o == nil || IsNil(o.BotOpenPct) {
		var ret float32
		return ret
	}
	return *o.BotOpenPct
}

// GetBotOpenPctOk returns a tuple with the BotOpenPct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSendingStats200ResponseStats) GetBotOpenPctOk() (*float32, bool) {
	if o == nil || IsNil(o.BotOpenPct) {
		return nil, false
	}
	return o.BotOpenPct, true
}

// HasBotOpenPct returns a boolean if a field has been set.
func (o *GetSendingStats200ResponseStats) HasBotOpenPct() bool {
	if o != nil && !IsNil(o.BotOpenPct) {
		return true
	}

	return false
}

// SetBotOpenPct gets a reference to the given float32 and assigns it to the BotOpenPct field.
func (o *GetSendingStats200ResponseStats) SetBotOpenPct(v float32) {
	o.BotOpenPct = &v
}

func (o GetSendingStats200ResponseStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSendingStats200ResponseStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	if !IsNil(o.Sent) {
		toSerialize["sent"] = o.Sent
	}
	if !IsNil(o.Delivered) {
		toSerialize["delivered"] = o.Delivered
	}
	if !IsNil(o.Bounced) {
		toSerialize["bounced"] = o.Bounced
	}
	if !IsNil(o.Deferred) {
		toSerialize["deferred"] = o.Deferred
	}
	if !IsNil(o.Failed) {
		toSerialize["failed"] = o.Failed
	}
	if !IsNil(o.OpenedTotal) {
		toSerialize["opened_total"] = o.OpenedTotal
	}
	if !IsNil(o.OpenedUnique) {
		toSerialize["opened_unique"] = o.OpenedUnique
	}
	if !IsNil(o.ClickedTotal) {
		toSerialize["clicked_total"] = o.ClickedTotal
	}
	if !IsNil(o.ClickedUnique) {
		toSerialize["clicked_unique"] = o.ClickedUnique
	}
	if !IsNil(o.Unsubscribed) {
		toSerialize["unsubscribed"] = o.Unsubscribed
	}
	if !IsNil(o.DeliveryRate) {
		toSerialize["delivery_rate"] = o.DeliveryRate
	}
	if !IsNil(o.OpenRate) {
		toSerialize["open_rate"] = o.OpenRate
	}
	if !IsNil(o.ClickRate) {
		toSerialize["click_rate"] = o.ClickRate
	}
	if !IsNil(o.BotOpens) {
		toSerialize["bot_opens"] = o.BotOpens
	}
	if !IsNil(o.HumanOpens) {
		toSerialize["human_opens"] = o.HumanOpens
	}
	if !IsNil(o.BotOpenPct) {
		toSerialize["bot_open_pct"] = o.BotOpenPct
	}
	return toSerialize, nil
}

type NullableGetSendingStats200ResponseStats struct {
	value *GetSendingStats200ResponseStats
	isSet bool
}

func (v NullableGetSendingStats200ResponseStats) Get() *GetSendingStats200ResponseStats {
	return v.value
}

func (v *NullableGetSendingStats200ResponseStats) Set(val *GetSendingStats200ResponseStats) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSendingStats200ResponseStats) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSendingStats200ResponseStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSendingStats200ResponseStats(val *GetSendingStats200ResponseStats) *NullableGetSendingStats200ResponseStats {
	return &NullableGetSendingStats200ResponseStats{value: val, isSet: true}
}

func (v NullableGetSendingStats200ResponseStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSendingStats200ResponseStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


