/*
MailOdds Email Validation API

MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

API version: 1.0.0
Contact: support@mailodds.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailodds

import (
	"encoding/json"
)

// checks if the SendingDomainIdentityScore type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendingDomainIdentityScore{}

// SendingDomainIdentityScore struct for SendingDomainIdentityScore
type SendingDomainIdentityScore struct {
	// Composite score 0-100
	OverallScore *float32 `json:"overall_score,omitempty"`
	Checks *SendingDomainIdentityScoreChecks `json:"checks,omitempty"`
}

// NewSendingDomainIdentityScore instantiates a new SendingDomainIdentityScore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendingDomainIdentityScore() *SendingDomainIdentityScore {
	this := SendingDomainIdentityScore{}
	return &this
}

// NewSendingDomainIdentityScoreWithDefaults instantiates a new SendingDomainIdentityScore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendingDomainIdentityScoreWithDefaults() *SendingDomainIdentityScore {
	this := SendingDomainIdentityScore{}
	return &this
}

// GetOverallScore returns the OverallScore field value if set, zero value otherwise.
func (o *SendingDomainIdentityScore) GetOverallScore() float32 {
	if o == nil || IsNil(o.OverallScore) {
		var ret float32
		return ret
	}
	return *o.OverallScore
}

// GetOverallScoreOk returns a tuple with the OverallScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendingDomainIdentityScore) GetOverallScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.OverallScore) {
		return nil, false
	}
	return o.OverallScore, true
}

// HasOverallScore returns a boolean if a field has been set.
func (o *SendingDomainIdentityScore) HasOverallScore() bool {
	if o != nil && !IsNil(o.OverallScore) {
		return true
	}

	return false
}

// SetOverallScore gets a reference to the given float32 and assigns it to the OverallScore field.
func (o *SendingDomainIdentityScore) SetOverallScore(v float32) {
	o.OverallScore = &v
}

// GetChecks returns the Checks field value if set, zero value otherwise.
func (o *SendingDomainIdentityScore) GetChecks() SendingDomainIdentityScoreChecks {
	if o == nil || IsNil(o.Checks) {
		var ret SendingDomainIdentityScoreChecks
		return ret
	}
	return *o.Checks
}

// GetChecksOk returns a tuple with the Checks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendingDomainIdentityScore) GetChecksOk() (*SendingDomainIdentityScoreChecks, bool) {
	if o == nil || IsNil(o.Checks) {
		return nil, false
	}
	return o.Checks, true
}

// HasChecks returns a boolean if a field has been set.
func (o *SendingDomainIdentityScore) HasChecks() bool {
	if o != nil && !IsNil(o.Checks) {
		return true
	}

	return false
}

// SetChecks gets a reference to the given SendingDomainIdentityScoreChecks and assigns it to the Checks field.
func (o *SendingDomainIdentityScore) SetChecks(v SendingDomainIdentityScoreChecks) {
	o.Checks = &v
}

func (o SendingDomainIdentityScore) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendingDomainIdentityScore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OverallScore) {
		toSerialize["overall_score"] = o.OverallScore
	}
	if !IsNil(o.Checks) {
		toSerialize["checks"] = o.Checks
	}
	return toSerialize, nil
}

type NullableSendingDomainIdentityScore struct {
	value *SendingDomainIdentityScore
	isSet bool
}

func (v NullableSendingDomainIdentityScore) Get() *SendingDomainIdentityScore {
	return v.value
}

func (v *NullableSendingDomainIdentityScore) Set(val *SendingDomainIdentityScore) {
	v.value = val
	v.isSet = true
}

func (v NullableSendingDomainIdentityScore) IsSet() bool {
	return v.isSet
}

func (v *NullableSendingDomainIdentityScore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendingDomainIdentityScore(val *SendingDomainIdentityScore) *NullableSendingDomainIdentityScore {
	return &NullableSendingDomainIdentityScore{value: val, isSet: true}
}

func (v NullableSendingDomainIdentityScore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendingDomainIdentityScore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


