/*
MailOdds Email Validation API

MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

API version: 1.0.0
Contact: support@mailodds.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailodds

import (
	"encoding/json"
)

// checks if the SuppressionStatsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SuppressionStatsResponse{}

// SuppressionStatsResponse struct for SuppressionStatsResponse
type SuppressionStatsResponse struct {
	SchemaVersion *string `json:"schema_version,omitempty"`
	Total *int32 `json:"total,omitempty"`
	ByType *SuppressionStatsResponseByType `json:"by_type,omitempty"`
}

// NewSuppressionStatsResponse instantiates a new SuppressionStatsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuppressionStatsResponse() *SuppressionStatsResponse {
	this := SuppressionStatsResponse{}
	return &this
}

// NewSuppressionStatsResponseWithDefaults instantiates a new SuppressionStatsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuppressionStatsResponseWithDefaults() *SuppressionStatsResponse {
	this := SuppressionStatsResponse{}
	return &this
}

// GetSchemaVersion returns the SchemaVersion field value if set, zero value otherwise.
func (o *SuppressionStatsResponse) GetSchemaVersion() string {
	if o == nil || IsNil(o.SchemaVersion) {
		var ret string
		return ret
	}
	return *o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuppressionStatsResponse) GetSchemaVersionOk() (*string, bool) {
	if o == nil || IsNil(o.SchemaVersion) {
		return nil, false
	}
	return o.SchemaVersion, true
}

// HasSchemaVersion returns a boolean if a field has been set.
func (o *SuppressionStatsResponse) HasSchemaVersion() bool {
	if o != nil && !IsNil(o.SchemaVersion) {
		return true
	}

	return false
}

// SetSchemaVersion gets a reference to the given string and assigns it to the SchemaVersion field.
func (o *SuppressionStatsResponse) SetSchemaVersion(v string) {
	o.SchemaVersion = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *SuppressionStatsResponse) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuppressionStatsResponse) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *SuppressionStatsResponse) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *SuppressionStatsResponse) SetTotal(v int32) {
	o.Total = &v
}

// GetByType returns the ByType field value if set, zero value otherwise.
func (o *SuppressionStatsResponse) GetByType() SuppressionStatsResponseByType {
	if o == nil || IsNil(o.ByType) {
		var ret SuppressionStatsResponseByType
		return ret
	}
	return *o.ByType
}

// GetByTypeOk returns a tuple with the ByType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuppressionStatsResponse) GetByTypeOk() (*SuppressionStatsResponseByType, bool) {
	if o == nil || IsNil(o.ByType) {
		return nil, false
	}
	return o.ByType, true
}

// HasByType returns a boolean if a field has been set.
func (o *SuppressionStatsResponse) HasByType() bool {
	if o != nil && !IsNil(o.ByType) {
		return true
	}

	return false
}

// SetByType gets a reference to the given SuppressionStatsResponseByType and assigns it to the ByType field.
func (o *SuppressionStatsResponse) SetByType(v SuppressionStatsResponseByType) {
	o.ByType = &v
}

func (o SuppressionStatsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuppressionStatsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SchemaVersion) {
		toSerialize["schema_version"] = o.SchemaVersion
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.ByType) {
		toSerialize["by_type"] = o.ByType
	}
	return toSerialize, nil
}

type NullableSuppressionStatsResponse struct {
	value *SuppressionStatsResponse
	isSet bool
}

func (v NullableSuppressionStatsResponse) Get() *SuppressionStatsResponse {
	return v.value
}

func (v *NullableSuppressionStatsResponse) Set(val *SuppressionStatsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSuppressionStatsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSuppressionStatsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuppressionStatsResponse(val *SuppressionStatsResponse) *NullableSuppressionStatsResponse {
	return &NullableSuppressionStatsResponse{value: val, isSet: true}
}

func (v NullableSuppressionStatsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuppressionStatsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


