/*
MailOdds Email Validation API

MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

API version: 1.0.0
Contact: support@mailodds.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailodds

import (
	"encoding/json"
)

// checks if the RemoveSuppression200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoveSuppression200Response{}

// RemoveSuppression200Response struct for RemoveSuppression200Response
type RemoveSuppression200Response struct {
	SchemaVersion *string `json:"schema_version,omitempty"`
	Removed *int32 `json:"removed,omitempty"`
}

// NewRemoveSuppression200Response instantiates a new RemoveSuppression200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoveSuppression200Response() *RemoveSuppression200Response {
	this := RemoveSuppression200Response{}
	return &this
}

// NewRemoveSuppression200ResponseWithDefaults instantiates a new RemoveSuppression200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoveSuppression200ResponseWithDefaults() *RemoveSuppression200Response {
	this := RemoveSuppression200Response{}
	return &this
}

// GetSchemaVersion returns the SchemaVersion field value if set, zero value otherwise.
func (o *RemoveSuppression200Response) GetSchemaVersion() string {
	if o == nil || IsNil(o.SchemaVersion) {
		var ret string
		return ret
	}
	return *o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoveSuppression200Response) GetSchemaVersionOk() (*string, bool) {
	if o == nil || IsNil(o.SchemaVersion) {
		return nil, false
	}
	return o.SchemaVersion, true
}

// HasSchemaVersion returns a boolean if a field has been set.
func (o *RemoveSuppression200Response) HasSchemaVersion() bool {
	if o != nil && !IsNil(o.SchemaVersion) {
		return true
	}

	return false
}

// SetSchemaVersion gets a reference to the given string and assigns it to the SchemaVersion field.
func (o *RemoveSuppression200Response) SetSchemaVersion(v string) {
	o.SchemaVersion = &v
}

// GetRemoved returns the Removed field value if set, zero value otherwise.
func (o *RemoveSuppression200Response) GetRemoved() int32 {
	if o == nil || IsNil(o.Removed) {
		var ret int32
		return ret
	}
	return *o.Removed
}

// GetRemovedOk returns a tuple with the Removed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoveSuppression200Response) GetRemovedOk() (*int32, bool) {
	if o == nil || IsNil(o.Removed) {
		return nil, false
	}
	return o.Removed, true
}

// HasRemoved returns a boolean if a field has been set.
func (o *RemoveSuppression200Response) HasRemoved() bool {
	if o != nil && !IsNil(o.Removed) {
		return true
	}

	return false
}

// SetRemoved gets a reference to the given int32 and assigns it to the Removed field.
func (o *RemoveSuppression200Response) SetRemoved(v int32) {
	o.Removed = &v
}

func (o RemoveSuppression200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoveSuppression200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SchemaVersion) {
		toSerialize["schema_version"] = o.SchemaVersion
	}
	if !IsNil(o.Removed) {
		toSerialize["removed"] = o.Removed
	}
	return toSerialize, nil
}

type NullableRemoveSuppression200Response struct {
	value *RemoveSuppression200Response
	isSet bool
}

func (v NullableRemoveSuppression200Response) Get() *RemoveSuppression200Response {
	return v.value
}

func (v *NullableRemoveSuppression200Response) Set(val *RemoveSuppression200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoveSuppression200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoveSuppression200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoveSuppression200Response(val *RemoveSuppression200Response) *NullableRemoveSuppression200Response {
	return &NullableRemoveSuppression200Response{value: val, isSet: true}
}

func (v NullableRemoveSuppression200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoveSuppression200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


